language: python

python:
  - "2.7"
  # - "pypy" Not all tests are working yet

env:
  - TEST_TARGET=master
  - TEST_TARGET=slave
  - TEST_TARGET=javascript

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libsasl2-dev libmysqlclient-dev libldap2-dev libssl-dev python-dev
  - if [ $TEST_TARGET = javascript]; then npm install -g grunt-cli; fi

before_script:
  - if [ "$TEST_TARGET" = "javascript" ]; then export TZ=Europe/Copenhagen; fi

install:
  - if [ "$TEST_TARGET" != "javascript" ]; then pip install -e www; fi
  - if [ "$TEST_TARGET" != "javascript" ]; then pip install -e $TEST_TARGET --process-dependency-links; fi
  - if [ "$TEST_TARGET" != "javascript" ]; then pip install -v mock; fi
  - if [ "$TEST_TARGET" != "javascript" ]; then pip install -v pyflakes; fi
  - if [ "$TEST_TARGET" != "javascript" ]; then pip install -v coveralls; fi
  - if [ "$TEST_TARGET" = "javascript" ]; then cd www/; fi
  - if [ "$TEST_TARGET" = "javascript" ]; then npm install; fi

script:
  - if [ "$TEST_TARGET" = "master" ]; then coverage run `which trial` buildbot.test; fi
  - if [ "$TEST_TARGET" = "slave" ]; then coverage run `which trial` buildslave; fi
  - if [ "$TEST_TARGET" = "javascript" ]; then grunt test; fi

after_success:
  - if [ "$TEST_TARGET" != "javascript" ]; then coveralls; fi
